GET http://localhost:5128/Items/0

GET http://localhost:5128/todos

###

POST http://localhost:5128/todos
Content-Type: application/json

{
    "id":2,
    "name": "Write another Demi",
    "dueDate": "2026-12-31",
    "isCompleted": false
}

###

GET http://localhost:5128/todos/2

###

DELETE http://localhost:5128/todos/2

###

GET http://localhost:5128/tasks/1

###

GET http://localhost:5128/api/Items/Categories

###

GET http://localhost:5128/api/Items/bulk

###

POST http://localhost:5128/ContollCosmos/Create
Content-Type: application/json

{
  "id": "das",
  "category": "dsa",
  "name": "ads",
  "quantity": 2,
  "price": 1,
  "clearance": true
}

###


DELETE http://localhost:5128/todos/2
